name = "sanath-portfolio"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
NODE_ENV = "production"

[[routes]]
pattern = "sanathcloud.com/*"
zone_name = "sanathcloud.com"

[[routes]]
pattern = "www.sanathcloud.com/*"
zone_name = "sanathcloud.com"

[assets]
directory = "./build"
binding = "ASSETS"